spring.application.name=server

#spring.datasource.url=jdbc:oracle:thin:@localhost:1521/XEPDB1
#spring.datasource.username=system
#spring.datasource.password=Oracle123
#spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true

# Enable H2 console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JDBC H2 settings
spring.datasource.url=jdbc:h2:mem:fooddb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Show SQL (optional)
spring.jpa.show-sql=true




